// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {PlasmicLoginForm} from "./plasmic/fusion_lab/PlasmicLoginForm";
import supabase from "../utils/supabase";

function LoginForm_(props, ref) {
    async function handleSubmit(event) {
        event.preventDefault();

        const email = event.target.email.value;

        await supabase.auth.signInWithOtp({email});
    }

    return (<PlasmicLoginForm>
        <div>
            <h1>Log In</h1>
            <form onSubmit={handleSubmit}>
                <label htmlFor="email">Email</label>
                <input type="email" id="email" name="email"/>
                <button type="submit">Log In</button>
            </form>
        </div>
    </PlasmicLoginForm>);
}

const LoginForm = React.forwardRef(LoginForm_);

export default LoginForm;
